import Link from "next/link";

export default function RegistryGuide() {
  return <section className="registry-guide" aria-labelledby="registry-guide-title">
    <div className="section-heading"><div><span className="section-kicker">How it works</span><h2 id="registry-guide-title">A public record of asset approval</h2></div></div>
    <p className="registry-guide-intro">The registry is a list of exact asset IDs approved by the CSWAP issuer and stored on Cardano Preprod. Anyone can read it or submit a refundable asset-admission request; only the configured issuer wallet can approve, reject, add, or revoke entries.</p>
    <ol className="registry-guide-steps">
      <li><span className="registry-guide-number" aria-hidden="true">1</span><h3>Choose an NFT</h3><p>Mint an NFT through <Link href="/mint">Mint RWA</Link>, or use an existing NFT minted with the supported CSWAP contract. Copy its asset ID: the policy ID followed by its asset name in hex.</p></li>
      <li><span className="registry-guide-number" aria-hidden="true">2</span><h3>Request or register approval</h3><p>Asset owners submit requests from <Link href="/portfolio/asset-requests">Portfolio → Asset support</Link> with a refundable deposit. The issuer reviews the pending request, checks every original mint, then approves the full batch atomically or rejects it. The issuer can also register a reviewed asset directly here.</p></li>
      <li><span className="registry-guide-number" aria-hidden="true">3</span><h3>Find approved assets</h3><p>Confirmed entries appear in the <Link href="/asset-registry">public approval list</Link>. Registry approval does not post a shared-pool price; a batcher must set an on-chain price and the pool needs available reserves before Instant Sell can be acquired.</p></li>
    </ol>
    <details><summary>What does registration or revocation change?</summary><div className="registry-guide-detail"><p>Registration records issuer approval. It does not transfer the NFT or guarantee its underlying real-world value. The on-chain contract enforces the issuer’s signature; mint-origin verification is performed by this app.</p><p><strong>Revoke approval</strong> removes the asset from the current registry after confirmation. It does not burn the asset, move it from its owner, cancel existing listings, or remove an independently posted pool price.</p><p>Approval applies to the exact asset ID. Fraction tokens need separate approval; this page currently verifies original NFTs only. Refresh to read the latest confirmed registry state.</p></div></details>
    <details><summary>Available configuration parameters</summary><div className="registry-guide-detail">
      <p>Set these in <code>.env.local</code> for local development, or in your hosting environment. Start with the network and Blockfrost project ID. Add both registry identifiers after the initialization transaction confirms.</p>
      <div className="registry-config-table-wrap" role="region" aria-label="Registry configuration parameters" tabIndex={0}><table className="registry-config-table"><caption>Registry settings and related services</caption><thead><tr><th scope="col">Parameter</th><th scope="col">When needed</th><th scope="col">Value and purpose</th></tr></thead><tbody>
        <tr><th scope="row"><code>NEXT_PUBLIC_CARDANO_NETWORK</code></th><td>Before setup</td><td>Set to <code>preprod</code>. The current registry flow supports Preprod only.</td></tr>
        <tr><th scope="row"><code>BLOCKFROST_PROJECT_ID</code></th><td>Before setup</td><td>Your Cardano Preprod project ID from Blockfrost. The server uses it to read chain state and submit transactions. Keep it server-only.</td></tr>
        <tr><th scope="row"><code>NEXT_PUBLIC_ASSET_REGISTRY_TOKEN</code></th><td>After setup</td><td>The registry identity NFT’s full asset ID: policy ID plus asset name in hex. Copy it from the confirmed deployment output.</td></tr>
        <tr><th scope="row"><code>NEXT_PUBLIC_ASSET_REGISTRY_ISSUER</code></th><td>After setup</td><td>The issuer’s 28-byte payment key hash, expressed as 56 hex characters. Copy it from the deployment output. This is a public key hash, not a wallet address or signing key.</td></tr>
        <tr><th scope="row"><code>NEXT_PUBLIC_SIMPLE_ORDERBOOK_ADDRESS</code></th><td>Marketplace integration</td><td>The deployed orderbook script address. It is separate from registry identity and is not required to manage approvals.</td></tr>
        <tr><th scope="row"><code>BLOCKFROST_IPFS_PROJECT_ID</code></th><td>Minting new NFTs</td><td>A separate Blockfrost IPFS project ID for image, proof, and metadata uploads on the mint page. Keep it server-only. Existing NFTs can be registered without it.</td></tr>
      </tbody></table></div>
      <p>Restart the development server after editing configuration. Rebuild a deployed app when changing <code>NEXT_PUBLIC_</code> values, because they are included in the browser bundle. Never place secret keys in a <code>NEXT_PUBLIC_</code> setting.</p>
      <p>The registry address is derived from its identity token, issuer hash, and compiled contract. There is no separate registry-address setting. Changing an environment value does not transfer control of an existing registry; it changes which deployment the app tries to read.</p>
      <p>The 50-asset limit is fixed in the contract. The revision counter and asset entries are on-chain state updated through registration and revocation, not environment parameters.</p>
    </div></details>
    <details><summary>First-time setup and registry limits</summary><div className="registry-guide-detail"><p>If no registry is configured, connect the intended issuer wallet on Preprod and select <strong>Create registry</strong>. After confirmation, save the transaction hash and add the displayed public configuration values to the app’s environment, then restart or rebuild the app.</p><p>This version supports up to <strong>50 assets</strong>. Updates require transaction fees and may need additional ADA as the list grows. The issuer cannot be changed, and the registry’s identity token and deposited ADA stay locked. Choose the issuer wallet before creating the registry.</p><p>If confirmation is delayed, use <strong>Check confirmation</strong> and the transaction link before retrying. Save the hash before leaving the page.</p></div></details>
  </section>;
}
